### ISSUE TITLE
Getting "exec /app/piped-proxy: exec format error"

### ISSUE THREAD

**Issue by Scorpoon** [TeamPiped/piped-proxy#291]
Starting the container will just show "exec /app/piped-proxy: exec format error" in the container logs, restarts afterwards

piped-proxy part of the compose file:
```
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        environment:
            - UDS=1
        volumes:
            - piped-proxy:/app/socket
        container_name: piped-proxy
```

pipedproxy.conf file:
```
server {
    listen 80;
    server_name pipedproxy.mydomain.com;

    location ~ (/videoplayback|/api/v4/|/api/manifest/) {
        include snippets/ytproxy.conf;
        add_header Cache-Control private always;
    }

    location / {
        include snippets/ytproxy.conf;
        add_header Cache-Control "public, max-age=604800";
    }
}
```

ytproxy.conf file:
```
proxy_buffering on;
proxy_buffers 1024 16k;
proxy_set_header X-Forwarded-For "";
proxy_set_header CF-Connecting-IP "";
proxy_hide_header "alt-svc";
sendfile on;
sendfile_max_chunk 512k;
tcp_nopush on;
aio threads=default;
aio_write on;
directio 16m;
proxy_hide_header Cache-Control;
proxy_hide_header etag;
proxy_http_version 1.1;
proxy_set_header Connection keep-alive;
proxy_max_temp_file_size 32m;
access_log off;
proxy_pass http://unix:/var/run/ytproxy/actix.sock;
```
